# Generated by Django 5.1.15 on 2026-09-18 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_servicecategory_holdback_days_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'verbose_name_plural': 'Service Categories'},
        ),
    ]
