# Generated by Django 5.1.15 on 2026-09-19 01:09

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_servicecategory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceoffer',
            name='quoted_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
