# Generated by Django 5.1.15 on 2026-09-18 20:08

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provideragreement',
            old_name='created_at',
            new_name='signed_at',
        ),
        migrations.RenameField(
            model_name='provideragreement',
            old_name='vision',
            new_name='version',
        ),
        migrations.AlterField(
            model_name='provider',
            name='service_area',
            field=models.CharField(blank=True, max_length=255, validators=[accounts.models.validate_not_blank]),
        ),
    ]
