# Generated by Django 5.1.15 on 2026-09-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_created_at_provideragreement_signed_at_and_more'),
        ('services', '0004_alter_serviceoffer_quoted_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='qualified_categories',
            field=models.ManyToManyField(blank=True, related_name='qualified_providers', to='services.servicecategory'),
        ),
    ]
