# Generated by Django 5.1.15 on 2026-09-18 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_rename_created_at_provideragreement_signed_at_and_more'),
        ('services', '0003_alter_servicecategory_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('awaiting_assignment', 'Awaiting provider assignment'), ('assigned', 'Provider assigned'), ('in-progress', 'In progress'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='awaiting_assignment', max_length=25)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('customer_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('offer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='booking', to='services.serviceoffer')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payout_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('offered', 'Offered to provider'), ('confirmed', 'Confirmed by provider'), ('declined', 'Declined by provider'), ('completed', 'Job completed')], default='offered', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='accounts.provider')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='assignment', to='bookings.booking')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='bookings.booking')),
            ],
        ),
    ]
